//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CircleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CircleService.ICircleService")]
    public interface ICircleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICircleService/CalcDiameter", ReplyAction="http://tempuri.org/ICircleService/CalcDiameterResponse")]
        double CalcDiameter(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICircleService/CalcDiameter", ReplyAction="http://tempuri.org/ICircleService/CalcDiameterResponse")]
        System.Threading.Tasks.Task<double> CalcDiameterAsync(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICircleService/CalcCirumference", ReplyAction="http://tempuri.org/ICircleService/CalcCirumferenceResponse")]
        double CalcCirumference(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICircleService/CalcCirumference", ReplyAction="http://tempuri.org/ICircleService/CalcCirumferenceResponse")]
        System.Threading.Tasks.Task<double> CalcCirumferenceAsync(double radius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICircleServiceChannel : Client.CircleService.ICircleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CircleServiceClient : System.ServiceModel.ClientBase<Client.CircleService.ICircleService>, Client.CircleService.ICircleService {
        
        public CircleServiceClient() {
        }
        
        public CircleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CircleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CircleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CircleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalcDiameter(double radius) {
            return base.Channel.CalcDiameter(radius);
        }
        
        public System.Threading.Tasks.Task<double> CalcDiameterAsync(double radius) {
            return base.Channel.CalcDiameterAsync(radius);
        }
        
        public double CalcCirumference(double radius) {
            return base.Channel.CalcCirumference(radius);
        }
        
        public System.Threading.Tasks.Task<double> CalcCirumferenceAsync(double radius) {
            return base.Channel.CalcCirumferenceAsync(radius);
        }
    }
}
